### ISSUE TITLE
Sorry, I am a novice, I don't know how to use this plug-in, can you help me

### ISSUE THREAD

**Issue by yimengZJl** [ChristopherSchultz/mirth-plugins#3]
Sorry, I am a novice, I don't know how to use this plug-in, can you help me

**Comment by ChristopherSchultz** [comment]
Which plug-in are you trying to use? There are several hosted here.

**Comment by thorst** [comment]
I'm trying to use the ldap, I assume this user would start there as well.

In your readme you speak to building it and also uploading a zip. Do we HAVE to build the project (it looks like yes) or is there a prebuilt zip that we are missing?

**Comment by ChristopherSchultz** [comment]
There is no pre-built ZIP file, so yes, you have to build it yourself.

**Comment by ChristopherSchultz** [comment]
You will also need to configure it using an `ldap.properties` file which should be in the same directory as your `mirth.properties` file. See the sample `ldap.properties` file for more information.
