### ISSUE TITLE
Multiple LDAP servers

### ISSUE THREAD

**Issue by alcir** [ChristopherSchultz/mirth-plugins#5]
Some services allow to specify more than one LDAP server for fallback. They are used in succession if the first doesn't work.
Is there a way to specify multiple LDAP servers?
Like `ldap.url=ldaps://ldap1.my.domain ldap2.my.domain:636/` or `ldap.url=ldaps://ldap1.my.domain:636,ldaps://ldap2.my.domain:636/`

Thanks.

**Comment by alcir** [comment]
Oh, ok. https://docs.oracle.com/javase/7/docs/technotes/guides/jndi/jndi-ldap-gl.html#URLS _To configure an LDAP service provider, you typically supply one or more space-separated LDAP or LDAPS URLs in the java.naming.provider.url property._
This should be the syntax.
`ldap.url=ldaps://ldap1.my.domain:636 ldaps://ldap2.my.domain:636/ ldaps://ldap3..my.domain:636/`
And it works.

**Comment by ChristopherSchultz** [comment]
I'd be happy to accept a documentation pull-request if you want to write one which describes how to configure multiple servers.
