### ISSUE TITLE
SSL manager plugin

### ISSUE THREAD

**Issue by marcheschi** [ChristopherSchultz/mirth-plugins#6]
Hi
First af all thank you for your great work !! 
This is not an issue but I did not find an email to address this question.
Do you know if is available an Opensource SSL manager plugin for Mirth connect.
At the moment we use stunnel, but a way to create tunnels from inside mirth could be a lot better.
Thank you 
Best Regards
Paolo Marcheschi

**Comment by jonbartels** [comment]
Tony G has a partial implementation (SSL listeners only) at https://github.com/tonygermano/connect-plugins

A quick writeup on the state of SSL in MC is at - https://gist.github.com/jonbartels/8abd121901eb930f46245d9ef0f5710e

If you find open source SSL options please reply back or post edits to that gist. 

(Disclaimer - I work for Zen who has a commercial SSL offering)

**Comment by marcheschi** [comment]
Hi @jonbartels 
Thank you very much for the links!!
Best regards
Paolo Marcheschi
