### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by NathanLeading** [ChristopherSchultz/mirth-plugins#7]
Chris,

We are trying to get the MFA plugin working but are running into several things. This is our first time building with Maven so bare with me. I wouldn't post an issue unless it was a last resort.

We've tried 3.12, 3.11 and 3.8 JAR files. We've also tried Maven 3.5 and the latest version of Maven.

We are building on MacOS, Maven installed through Brew - I will try through linux in case that is the issue and if it gets fixed I will let you know.

## Maven build error:

```[ERROR] /Users/username/chris/mfa-auth/src/main/java/net/christopherschultz/mirth/plugins/auth/mfa/MFAAuthenticatorPlugin.java:[32,8] net.christopherschultz.mirth.plugins.auth.mfa.MFAAuthenticatorPlugin is not abstract and does not override abstract method getObjectsForSwaggerExamples() in com.mirth.connect.plugins.ServicePlugin```

## Version issue:

Your builder in mirth-plugins repo calls for `java-totp-1.0.jar`, but your totp repo builds `java-totp-1.1.jar`. We've tried going back to a really old commit where you have 1.0 as the version and building the 1.0 version, that did not change the above error. We also tried renaming `java-totp-1.1.jar` to `java-totp-1.0.jar` - this still gives the same error.

## Duplicate jar files issue:

Duplicate `mirth-client-core.jar` files found. Do we use the `mirth-client-core.jar` from `server` or `client` in the supported Mirth tgz download from the official connect repo?

I really appreciate your help!

Thank you!

**Comment by NathanLeading** [comment]
Here is a more detailed log of the error:

```Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
/Users/user/dev/www/mirth-docker/extensions/chris/mfa-auth/src/main/java/net/christopherschultz/mirth/plugins/auth/mfa/MFAAuthenticatorPlugin.java:[32,8] net.christopherschultz.mirth.plugins.auth.mfa.MFAAuthenticatorPlugin is not abstract and does not override abstract method getObjectsForSwaggerExamples() in com.mirth.connect.plugins.ServicePlugin

    at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1215)
    at org.apache.maven.plugin.compiler.CompilerMojo.execute (CompilerMojo.java:188)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
```

**Comment by ChristopherSchultz** [comment]
It looks like Mirth has changed an interface. They should have added a method using a default implementation, but they did not. The problem is not with the totp version. The problem is with the Mirth version you are building against.

I'll look at their new interface and see what needs to be added.

You should have been able to compile against Mirth 3.8. I'm curious as to why that doesn't work.

**Comment by ChristopherSchultz** [comment]
Hmm, something is amiss, here.

That interface can be found here https://github.com/nextgenhealthcare/connect/blob/3.12.x/server/src/com/mirth/connect/plugins/ServerPlugin.java

No changes for 8 years. No method called getObjectsForSwaggerExamples.

What are you using to compile against?

**Comment by jonbartels** [comment]
I may have found a solution that simplifies this for a new user. I hope this helps and does not confuse the issue.

Build process:
1. Clone https://github.com/ChristopherSchultz/java-totp; build it with `mvn clean install` . Grab the JAR from `./target` and copy it to `mfa-auth/libs`
2. Swap the `mfa-auth` `pom.xml` file for the one I attached. Rename it from .txt to .xml 
[pom.txt](https://github.com/ChristopherSchultz/mirth-plugins/files/7524375/pom.txt)
3. Build `mfa-auth` with `mvn clean install`

Details:

@kpalang has published an open Nexus repository where the MC artifacts are hosted. He is missing a few MC versions but it works. You'll note I changed from 3.8.0 to 3.8.1 because of this. This is helpful for projects like mfa-auth because one can just use the repo and avoid copying MC JARs around. You can see an example at https://github.com/kpalang/mirth-transmissionmode-cube30touch . 

I updated the java-totp version from 1.0 to 1.1. I assume there are no breaking changes. EDIT - I'm a dummy, I probably built the 1.1 SNAPSHOT and not the 1.0 release.

I also updated the pom to use a property for the MC version. I also set several of the dependencies to the provided scope since they will be available to the plugin from MC at runtime. 

This process let me build and compile the mfa-auth project. I have not deployed and tested it. I happened to compile this on a Mac with `openjdk version "13" 2019-09-17`  and Maven 3.6.2. I honestly just used whatever was laying around. 

If this works I'll submit a proper PR. I hope it helps get a new user started on the project.

@NathanLeading - Ignoring the above shortcut, information that might help debug your reported issue would be to run `md5 libs/*` and show the output. That will determine if you moved the correct files to build the project.

**Comment by NathanLeading** [comment]
Hey guys thank you for jumping in to respond quickly. I am going to take another shot at trying to compile this plugin and get back to you.

**Comment by NathanLeading** [comment]
Hey again! So the problem was caching. Perhaps in the `./bundle.sh` you should include `mvn clean` as a pre-build command. 

It looks like the latest supported version is 3.8 for Mirth. I tried 3.12, 3.11, 3.10 and 3.9 before getting to 3.8 that worked.

`mvn clean install` did the trick. Just in case I ran ./bundle.sh afterwards. I now have cschultz-mfa-auth-0.1.jar

Will this JAR file work only on 3.8 or do you think it will work on 3.11 or 3.12?

@ChristopherSchultz What would it take to get to 3.12 or 3.11?

Thanks for all your hard work guys!

**Comment by tonygermano** [comment]
@ChristopherSchultz is exactly right that they modified an interface and did not add a default implementation. What's even more infuriating is that every implementation of the new interface just returns null, which couldn't be a better use-case for a default implementation.

This change was as of mirth 3.9.0. https://github.com/nextgenhealthcare/connect/commit/bc9c18f7392644438aa765b0f7fa4e164c93f8d1#diff-8e42b16d31e2e65381312868826969b3f7a4c38e4770598d916af36f877b8418

@NathanLeading adding this method to `MFAAuthenticatorPlugin.java` should allow it to build.

```java
        @Override
        public Map<String, Object> getObjectsForSwaggerExamples() {
        	return null;
        }
```

**Comment by NathanLeading** [comment]
I was able to build for 3.12 using @tonygermano's modification, however I am stuck on signing the file with ./bundle.sh.

jarsigner is looking for:  mfa-auth/**keystore.p12**

```
jarsigner error: java.lang.RuntimeException: keystore load: /Users/nathanhuebner/dev/www/mirth-docker/extensions/chris/mfa-auth/keystore.p12 (No such file or directory)
  adding: cschultz-mfa-auth/ (stored 0%)
  adding: cschultz-mfa-auth/cschultz-mfa-auth-server.jar (deflated 16%)
  adding: cschultz-mfa-auth/plugin.xml (deflated 58%)
  adding: cschultz-mfa-auth/README.md (deflated 51%)
  adding: cschultz-mfa-auth/java-totp-1.0.jar (deflated 17%)
  adding: cschultz-mfa-auth/cschultz-mfa-auth-client.jar (deflated 16%)
```

**Comment by NathanLeading** [comment]
An update to the jarsigner - I went through all the steps but created a self-signed cert:

I also updated the plugin.xml to accept version 3.12 because 3.11 doesn't work in docker at all. I was able to install the plugin but after restarting the server it does not show up in the plugins list. I will be looking into the next "legs" of documentation to see if there are quirks there I need to address.

Any feedback on my use of 3.12 would be appreciated. Am I going down the wrong path, should we turn back and head to 3.11?

```
Warning: 
The signer certificate's ExtendedKeyUsage extension doesn't allow code signing.
The signer's certificate is self-signed.
POSIX file permission and/or symlink attributes detected. These attributes are ignored when signing and are not protected by the signature.
  adding: cschultz-mfa-auth/ (stored 0%)
  adding: cschultz-mfa-auth/cschultz-mfa-auth-server.jar (deflated 15%)
  adding: cschultz-mfa-auth/plugin.xml (deflated 58%)
  adding: cschultz-mfa-auth/README.md (deflated 51%)
  adding: cschultz-mfa-auth/java-totp-1.0.jar (deflated 17%)
  adding: cschultz-mfa-auth/cschultz-mfa-auth-client.jar (deflated 15%)
```

**Comment by NathanLeading** [comment]
@ChristopherSchultz I would be happy to write up a setup document after we get this working - such as:

 - Which files to pull from the `connect` repository and how to get them.
 - How to create the `keystore.p12` file.
 - How to install the plugin to Mirth Administrator

If we can get this working it would save our team a lot of problems, we want to see your hard work in action for sure.

**Comment by kpalang** [comment]
@NathanLeading @ChristopherSchultz I'm going to take this opportunity to suggest this official unofficial maven repository for mirth jar files https://nexus.kaurpalang.com/#browse/browse:maven-public:com%2Fmirth . May be of use when dealing with jars. These jars are in no way edited or tampered with, just downloaded from Mirth's GitHub and uploaded. If you have any questions, tag me in Slack in #plugin_development with the username @CreepySheep

**Comment by NathanLeading** [comment]
@ChristopherSchultz Here's a screenshot of the plugin on 3.11, the same screenshot as 3.12. 

We're going to keep stepping backwards until 3.8 - but we really would like to be on 3.10+ because of security updates. 

Let me know your thoughts.

Thanks!
![Screen Shot 2021-11-12 at 2 20 56 PM](https://user-images.githubusercontent.com/90629247/141529949-9ec23606-1e1a-4de0-89d4-e17f056932e5.png)

**Comment by NathanLeading** [comment]
I'm wondering if it has to do with the jarsigner?  I digged up my company's *.domain CRT+Key and created a p12 file, but got this when I tried using jarsigner:

Side note, I had to use sudo with the `bundle.sh` or it would fail on `variable: status`.

```Warning: 
The signer certificate's ExtendedKeyUsage extension doesn't allow code signing.
The signer's certificate chain is invalid. Reason: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2022-09-20).
POSIX file permission and/or symlink attributes detected. These attributes are ignored when signing and are not protected by the signature.

The signer certificate will expire on 2022-09-20.
  adding: cschultz-mfa-auth/ (stored 0%)
  adding: cschultz-mfa-auth/cschultz-mfa-auth-server.jar (deflated 14%)
  adding: cschultz-mfa-auth/plugin.xml (deflated 58%)
  adding: cschultz-mfa-auth/README.md (deflated 51%)
  adding: cschultz-mfa-auth/java-totp-1.0.jar (deflated 17%)
  adding: cschultz-mfa-auth/cschultz-mfa-auth-client.jar (deflated 14%)```

**Comment by tonygermano** [comment]
A code signing certificate is different than a cert you would use to protect a website. The underlying technology is the same, but different flags are set for what the cert is allowed to be used for.

**Comment by NathanLeading** [comment]
I'm not sure if the issue is caused by the jarsigner or if the MFA plugin doesn't work in 3.12 or 3.11. 

I've tried installing 3.8 for docker but I get `jnlp jar resources in jnlp file are not signed by same certificate` from Java, and there's only 2 posts on the web for this with mirth, clearing my certificates in Java does not fix it.

I'm close to giving up - I'm around 16 hours in on this. If anyone has some advice on what the problem could be let me know.

@ChristopherSchultz Let me know if you think you could make this plugin work in 3.11 or 3.12.

Thanks for your time guys, have a great weekend!

**Comment by ChristopherSchultz** [comment]
Okay, I've fixed a handful of things:
1. I have added the missing interface method to the plug-in
2. plugin.xml now includes the new versions of Mirth Connect
3. The TOTP library now uses the proper version
3. The plugin-bundling step is now documented in the README

**Comment by ChristopherSchultz** [comment]
> That interface can be found here https://github.com/nextgenhealthcare/connect/blob/3.12.x/server/src/com/mirth/connect/plugins/ServerPlugin.java

Sorry, I had the wrong class. It's Serv _ice_ Plugin.java, which is here:
https://github.com/nextgenhealthcare/connect/blob/3.12.x/server/src/com/mirth/connect/plugins/ServicePlugin.java

**Comment by ChristopherSchultz** [comment]
You should not have to run the bundle.sh script as `root`. Generally, running things as `root` is a Bad Idea.

**Comment by NathanLeading** [comment]
@ChristopherSchultz I'm going to give it another shot, thanks!

**Comment by NathanLeading** [comment]
@ChristopherSchultz Agreed on root not being a good idea, but I get this error run without root:

```./bundle.sh:19: read-only variable: status```

**Comment by NathanLeading** [comment]
@ChristopherSchultz I think all that's left is the reason we have to run as root -- I SUCCESSFULLY used your plugin.

It's awesome!

**Comment by NathanLeading** [comment]
Your readme for TOTP might be out of date, Mirth uses UPPERCASE on its columns now:

Here's a copy of what I used:

```
INSERT INTO PERSON_PREFERENCE (PERSON_ID, NAME, VALUE)
  VALUES (1, 'net.christopherschultz.mirth.plugins.auth.mfa-config', 'otpauth://URI')
;
```

**Comment by NathanLeading** [comment]
@ChristopherSchultz I am closing this task. Thank you for all your hard work and have a Happy Thanksgiving.

PS: We would like to buy you a cup of coffee or something, so can you send me your Venmo or Zelle.

You can reach me here:  ndallas1983@gmail.com
